// Icon catalog helpers. The catalog is generated by scripts/build-icon-catalog.mjs
// and served from /icons/catalog.json. Most SVGs come from the Simple Icons CDN;
// brands removed from Simple Icons (e.g. LinkedIn) are served from /icons/<slug>.svg.

export interface CatalogIcon {
  slug: string;
  title: string;
  hex: string;
  local?: boolean;
}

const LOCAL_ICON_SLUGS = new Set(["linkedin"]);

export function isLocalIcon(slug: string): boolean {
  return LOCAL_ICON_SLUGS.has(slug);
}

/** URL that returns the raw SVG for an icon (used for geometry and previews). */
export function iconSvgUrl(slug: string): string {
  return isLocalIcon(slug)
    ? `/icons/${slug}.svg`
    : `https://cdn.simpleicons.org/${encodeURIComponent(slug)}`;
}

let catalogPromise: Promise<CatalogIcon[]> | null = null;

export function loadCatalog(): Promise<CatalogIcon[]> {
  if (!catalogPromise) {
    catalogPromise = fetch("/icons/catalog.json").then((r) => {
      if (!r.ok) throw new Error("Failed to load icon catalog");
      return r.json();
    });
  }
  return catalogPromise;
}
