// Icon catalog helpers. The catalog is generated by scripts/build-icon-catalog.mjs
// and served from /icons/catalog.json. It holds the featured brand logos
// (Simple Icons CDN; LinkedIn locally from /icons/<slug>.svg since it was
// removed from Simple Icons) plus the Font Awesome Free solid set, whose
// slugs carry an fa- prefix and resolve to the jsDelivr CDN.

export interface CatalogIcon {
  slug: string;
  title: string;
  hex: string;
  local?: boolean;
}

// Must match FA_VERSION in scripts/build-icon-catalog.mjs.
const FA_VERSION = "6.7.2";

const LOCAL_ICON_SLUGS = new Set(["linkedin"]);

export function isLocalIcon(slug: string): boolean {
  return LOCAL_ICON_SLUGS.has(slug);
}

/** URL that returns the raw SVG for an icon (used for geometry and previews). */
export function iconSvgUrl(slug: string): string {
  if (isLocalIcon(slug)) return `/icons/${slug}.svg`;
  if (slug.startsWith("fa-"))
    return `https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@${FA_VERSION}/svgs/solid/${encodeURIComponent(slug.slice(3))}.svg`;
  return `https://cdn.simpleicons.org/${encodeURIComponent(slug)}`;
}

/** Inline an SVG string as an <img>-renderable data URL (for AI icon previews). */
export function svgToDataUrl(svg: string): string {
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

let catalogPromise: Promise<CatalogIcon[]> | null = null;

export function loadCatalog(): Promise<CatalogIcon[]> {
  if (!catalogPromise) {
    catalogPromise = fetch("/icons/catalog.json").then((r) => {
      if (!r.ok) throw new Error("Failed to load icon catalog");
      return r.json();
    });
  }
  return catalogPromise;
}
